### PR TITLE
Fix Windows SDK install

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Also reduces the size of the image a bit
- Install 7z to tempdir so it gets deleted
- Delete x86 directories from Program Files
- Delete some docs and man pages
- Delete ProgramData/Package Cache

Tested locally to ensure Envoy still builds

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
cc @wrowe

**Comment by sunjayBhatia** [comment]
cc @lizan This should fix your build error in https://github.com/envoyproxy/envoy-build-tools/pull/94

**Comment by sunjayBhatia** [comment]
we're going to push another commit to fix some miscellaneous comments

/wait

**Comment by lizan** [comment]
@sunjayBhatia is this ready? can you merge master?

**Comment by sunjayBhatia** [comment]
@lizan yep this is ready

**Pull request merged**
