### PR TITLE
Revert "Install Java 8, Android command line tools and SDK for Ubuntu"

### PR DESCRIPTION
**Pull request by jpsim**
Reverts envoyproxy/envoy-build-tools#188

This grew the Docker image by an unreasonable amount, going from 1.79 GB to 3.77 GB.

### CODE REVIEW

**Comment by phlax** [comment]
lgtm, but needs DCO

**Comment by jpsim** [comment]
> lgtm, but needs DCO

I created the revert using GitHub's UI. Is there a way to configure it to apply signoff when that's used? Or is it necessary to sign off locally?

**Comment by phlax** [comment]
not sure if there is a way to get gh to do it - i dont use it for that reason - i think you have to sign it off locally

**Review by phlax — APPROVED** [review]
lgtm, thanks @jpsim

**Comment by jpsim** [comment]
FYI I don't have merge access on this repo.

**Pull request merged**
