### PR TITLE
Redo Linux clang 11 bump

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Reapplies https://github.com/envoyproxy/envoy-build-tools/pull/116 which had to be reverted as it was merged too early

Also bumps Windows LLVM to 11.0.1 and adds Bazel 4.0.0 toolchain generation

### CODE REVIEW

**Comment by wrowe** [comment]
Let's expect to sync this update with https://github.com/envoyproxy/envoy-build-tools/pull/115

**Comment by wrowe** [comment]
/retest

I might not have perms to do this, @sunjayBhatia

**Comment by sunjayBhatia** [comment]
Looks like the 11.0.0 16.04 binaries are not on the releases page anymore, will need to update to 20.04

**Comment by wrowe** [comment]
> the 11.0.0 16.04 binaries are not on the releases page anymore

A compromise position would be to bump to 18.04, but I think it's a little late for that. Good call, time to jump to this decade.

**Comment by sunjayBhatia** [comment]
cc @lizan this is green if you get a chance to look

**Review by wrowe — COMMENTED** [review]
Can we pick up 11.0.1 windows and mac at the same time and begin keeping these in-sync?

Should we pick back up bazel 4.0.0+3.7.2 in the process?

**Review by lizan — APPROVED** [review]

**Comment by lizan** [comment]
yeah since bazel 4.0 is released let's pick up it.

**Review by lizan — APPROVED** [review]

**Pull request merged**
