### PR TITLE
Windows: Install OpenSSL standalone

### PR DESCRIPTION
**Pull request by sunjayBhatia**
Solves msys2 openssl fork/DLL base address issues in RBE

See: https://github.com/envoyproxy/envoy/pull/13276

Downloads OpenSSL installer from here: https://slproweb.com/products/Win32OpenSSL.html

Should be same installer used by chocolatey (https://chocolatey.org/packages/openssl#files) and mentioned on OpenSSL site: https://wiki.openssl.org/index.php/Binaries

### CODE REVIEW

**Comment by lizan** [comment]
@sunjayBhatia why do we need openssl in those tests?

**Comment by sunjayBhatia** [comment]
> @sunjayBhatia why do we need openssl in those tests?

There are a few scripts in these tests that generate test data on the fly, see this tree: https://github.com/envoyproxy/envoy/tree/master/test/extensions/transport_sockets/tls

specifically invocations show up here: https://github.com/envoyproxy/envoy/blob/db1a35213aa18399ba14ef545fc4894545cf68a2/test/extensions/transport_sockets/tls/ssl_certs_test.h

**Comment by sunjayBhatia** [comment]
@lizan do you prefer to have all the certs checked in? (imo its sorta nice to have things generated on the fly, makes sure we don't have to think about expiry dates and it keeps the tree cleaner, but its not a strong preference)

**Comment by lizan** [comment]
@sunjayBhatia yeah I think we had issue before with macOS so we checked in most of the certs. Or we can use the `bssl` binary from BoringSSL to accommodate those tests.

**Comment by sunjayBhatia** [comment]
> @sunjayBhatia yeah I think we had issue before with macOS so we checked in most of the certs. Or we can use the `bssl` binary from BoringSSL to accommodate those tests.

From what I’ve looked at `bssl` doesn’t have all the functionality of `openssl` and doesn’t look like it can generate x509 certs?

**Comment by sunjayBhatia** [comment]
@lizan would you prefer a change to check in the certs rather than this one? it has an added benefit of ensuring the tests are runnable on macos if they arent already

**Comment by sunjayBhatia** [comment]
@envoyproxy/build-tools-maintainers PTAL, the alternative to this change to the build image is to check in all generated certs in the `//test/extensions/transport_sockets/tls/...` set of tests

**Comment by lizan** [comment]
OK if bssl doesn't work I don't have strong preference. In general I'd like to avoid openssl though.

**Comment by sunjayBhatia** [comment]
See https://github.com/envoyproxy/envoy/pull/13702 as an alternative to updating OpenSSL

**Review by moderation — COMMENTED** [review]
Definitely @lizan 's area so will defer to him

**Comment by sunjayBhatia** [comment]
superceded by https://github.com/envoyproxy/envoy/pull/13702

**Pull request closed without merging**
