### PR TITLE
Update ndk to get C++20 on android

### PR DESCRIPTION
**Pull request by kyessenov**

### CODE REVIEW

**Review by adisuissa — APPROVED** [review]
LGTM, thanks for working on the path towards c++20 support.
Assigning a maintainer from Envoy-Mobile, as it impacts their project the most.
/assign @abeyad

**Comment by abeyad** [comment]
thanks @kyessenov !  

Question: Do we also need to update this for CI? https://github.com/envoyproxy/envoy/blob/8e93d16d433d3364c2b000dc9067ffc400e8f0d6/mobile/ci/linux_ci_setup.sh#L12

cc @fredyw @phlax if they see any concerns

**Comment by phlax** [comment]
@abeyad afaict that script is unused and can be removed

**Comment by abeyad** [comment]
> @abeyad afaict that script is unused and can be removed

SG, I'll send a PR to remove it

**Review by abeyad — APPROVED** [review]

**Pull request merged**
