### PR TITLE
add buildifier and buildozer for arm64

### PR DESCRIPTION
**Pull request by ramaraochavali**
Signed-off-by: Rama Chavali <rama.rao@salesforce.com>

### CODE REVIEW

**Comment by ramaraochavali** [comment]
@envoyproxy/build-tools-maintainers can you please take a look?

**Review by phlax — APPROVED** [review]
thanks @ramaraochavali 

ideally we shift these to being bazel targets for all platforms, but this gives equivalence for current approach so lgtm

headsup that the build image pipeline is currently stalled while we work out distro/version support

**Comment by ramaraochavali** [comment]
@phlax Any work is needed to pull this in to envoy main? or is it automated?

**Comment by phlax** [comment]
current blocked pr to update (this will supersede it) https://github.com/envoyproxy/envoy/pull/21388

**Pull request merged**
