### PR TITLE
WIP: Build bazel 5.0.0 toolchains

### PR DESCRIPTION
**Pull request by kfaseela**

### CODE REVIEW

**Review by wrowe — CHANGES_REQUESTED** [review]
See toolchains/regenerate.sh, used to be around line 40-45.

Previously, this would iterate for several co-existing bazel *versions*, it appears this patch iterates on *target architectures* but dropped iterating on parallel acceptable bazel versions? That is immediately problematic, but it seems it will be problematic on into the future.

**Comment by kfaseela** [comment]
> See toolchains/regenerate.sh, used to be around line 40-45.
> 
> Previously, this would iterate for several co-existing bazel _versions_, it appears this patch iterates on _target architectures_ but dropped iterating on parallel acceptable bazel versions? That is immediately problematic, but it seems it will be problematic on into the future.

@wrowe : this previous PR seems to have removed this capability? https://github.com/envoyproxy/envoy-build-tools/pull/143

**Comment by yanavlasov** [comment]
I do not think we need this 2 version dance. This PR should just be submitted and and new images generated at which point you can try to change Envoy to use new toolchain. If something does not work, then this PR can be either reverted or changed to address the problem.

**Comment by yanavlasov** [comment]
@lizan for approval and merge

**Pull request merged**
