### PR TITLE
upgrade llvm version for centos builds

### PR DESCRIPTION
**Pull request by angelahning**

### CODE REVIEW

**Comment by keith** [comment]
note the `LLVM_SHA256SUM` variables below this will also have to change since those are used to build up the URL and validate it https://github.com/envoyproxy/envoy-build-tools/blob/0f17a22c7902e21e5e003f5296adb628d2f16b2f/build_container/build_container_common.sh#L71

**Comment by angelahning** [comment]
> note the `LLVM_SHA256SUM` variables below this will also have to change since those are used to build up the URL and validate it
> 
> https://github.com/envoyproxy/envoy-build-tools/blob/0f17a22c7902e21e5e003f5296adb628d2f16b2f/build_container/build_container_common.sh#L71

dumb question: where may I find the corresponding `LLVM_SHA256SUM` for version 14?

**Comment by keith** [comment]
if it's not present on the releases page you'll have to download the files and compute them yourself with something like `sha256sum path/to/archive`

**Comment by angelahning** [comment]
> if it's not present on the releases page you'll have to download the files and compute them yourself with something like `sha256sum path/to/archive`

Thanks! I am now getting a new error in the centos container build  and I am not sure how to fix it ```https://dev.azure.com/cncf/envoy/_build/results?buildId=124982&view=logs&j=4a20cfb0-b4c4-5a53-b9a1-e1aff4b8582e&t=ab67d215-9fd8-552a-6b98-82215e89f164&l=2070```. I noticed that you previously upgraded llvm for the windows and linux build https://github.com/envoyproxy/envoy-build-tools/pull/171. Did you run into similar problems?

**Comment by keith** [comment]
hrm i didn't, it must be that the update is major enough that something else needs to change in the centos image because this required library is missing? i'd assume it's expecting a different version or something. You can debug a bit faster locally by running `docker build -f build_container/Dockerfile-centos build_container` directly. Or launching a centos docker image and running the scripts directly

**Comment by angelahning** [comment]
the centos container is now failing with ```#12 288.6 /opt/llvm/bin/llvm-config: error while loading shared libraries: libc++abi.so.1: cannot open shared object file: No such file or directory```

**Comment by keith** [comment]
similar issue i'd think

**Pull request closed without merging**
