### PR TITLE
Revert "Generate only one toolchain for specific bazel version"

### PR DESCRIPTION
**Pull request by yanavlasov**
First part of the revert to using RBE toolchain generator. The clang-cl build does not work using the 4.1 bazel toolchain and needs to be diagnosed with the RBE team.

Reverts envoyproxy/envoy-build-tools#143

Signed-off-by: Yan Avlasov yavlasov@google.com

### CODE REVIEW

**Review by wrowe — APPROVED** [review]
Question, is it more sensible to pause our clang-cl pipeline, continuing to build with msvc-cl, and focus on moving forwards from here including troubleshooting clang-cl compilation?

**Comment by wrowe** [comment]
So here's the issue, this commit failed to push a new image for docker image envoyproxy/envoy-build-windows2019:bb5c64, the most recent image on dockerhub is still a5bc79. So, accepting this revert until we can work out what broke in the image generation or docker push, since it has no corresponding windows build image.

**Comment by wrowe** [comment]
Since we haven't actually updated envoyproxy/envoy to consume these new images, (see notes on https://github.com/envoyproxy/envoy-build-tools/issues/147) can we leave this in place and diagnose why the docker hub build toolchains weren't updated? Any thoughts @yanavlasov @phlax or @lizan ?

**Comment by phlax** [comment]
its saying that the image exists here https://dev.azure.com/cncf/envoy/_build/results?buildId=88492&view=logs&j=f35ccc9a-a964-5625-3fa7-11d864af8f17&t=68e202c6-ae2b-5978-e578-5c9d1c68b5b7&l=17

is it possible that nothing changed with image in this commit ?

i would minded to land it and follow up

the alternative, if we want to get envoy update to date with the build image (i do) then we can update only the build image there

i get that this is a bit like "crossing the streams" but i think in reality it would be no different, ie - landing this and updating all <> not landing this and only updating image

**Comment by wrowe** [comment]
Note from the Ubuntu log .. 
envoyproxy/envoy-build-ubuntu:a4bc794b2b87e01cff1c5fe9f9a118b64b0759ce

That isn't the image we wanted it to push, it's using a stale tag. Did we miss something with checking the commit on master rather than main perhaps? Or why else would we be referencing commit n-3?

**Comment by phlax** [comment]
is it referencing the last real commit ? ie not automated from ci (as a suggestion)

**Comment by wrowe** [comment]
It should reference the last true commit bb5c64.

https://github.com/envoyproxy/envoy-build-tools/commits/main

**Comment by phlax** [comment]
i see, scrap that theory - its hard to rem how this repo works

**Comment by yanavlasov** [comment]
Toolchain generation script uses the SHA of the last commit in the build-container directory for the build image name. The last commit there was a4bc79

**Comment by yanavlasov** [comment]
Forced push to fix DCO.

**Comment by yanavlasov** [comment]
> Question, is it more sensible to pause our clang-cl pipeline, continuing to build with msvc-cl, and focus on moving forwards from here including troubleshooting clang-cl compilation?

I'm not sure, as I do not know how valuable clang-cl is to Windows devs, and how easy it is to disable it in CI.

**Comment by wrowe** [comment]
We can do an llvm bump which may clear up the clang-cl fault you observed, and then test pushing to that version of clang for our build images and envoy build. That can help validate that this solution will work so we don't dwell on the legacy approach anymore. See https://github.com/envoyproxy/envoy-build-tools/pull/139 for suggested bump.

**Comment by wrowe** [comment]
This has collided with other commits in the meantime, if you are still able to merge main?

Discussion on '#envoy-build-tools' of reverting the drop of parallel bazel version support.

**Pull request closed without merging**
