### PR TITLE
Windows build image: Install CMake and ninja outside of VS Build Tools

### PR DESCRIPTION
**Pull request by sunjayBhatia**
- VS BuildTools provides a 32-bit build of CMake, to ensure no
  unexpected results in different build environments, use CMake project
  provided 64-bit build
- Versions of these tools are easier to control installed standalone

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
cc @wrowe

**Comment by sunjayBhatia** [comment]
@lizan these failures might be relevant to you, the PR is only 1 commit ahead of master and only changed the Windows image build script; if they seem like just flakes we can kick off the build again with an empty commit

**Comment by lizan** [comment]
it is failing at download phase so could be just a flake.

**Comment by sunjayBhatia** [comment]
@lizan seems like this PR and this other one https://github.com/envoyproxy/envoy-build-tools/pull/50 are suffering from the same download failures on the ubuntu/centos image builds, seems like https://github.com/envoyproxy/envoy-build-tools/blob/65a079a4b8b1e0511216e59968754a64934cbab9/build_container/build_container_common.sh#L56 could have a retry or some other URL?

**Comment by sunjayBhatia** [comment]
@lizan this and the other Windows image PRs should be ready to go, all merged master

**Pull request merged**
