### PR TITLE
MUST: Bump bazel-toolchains in both repositories

### PR DESCRIPTION
**Pull request by wrowe**
- envoy/bazel/repository_locations.bzl (previously done)
 - envoy-build-tools/WORKSPACE (overlooked)

Signed-off-by: William A Rowe Jr <wrowe@vmware.com>

### CODE REVIEW

**Comment by wrowe** [comment]
@PiotrSikora I think you overlooked this, please validate.
@mattklein123 lizan is ooo so need you to do the honors unless you will sign off and perhaps I can, after CI

I *hope* we can borrow the version = attribute logic from envoy's repository_locations.bzl, crossing fingers.

**Review by PiotrSikora — APPROVED** [review]
This looks fine, but it would be helpful if you could mention what are you trying to fix, since changes to the `WORKSPACE` file affect only this repo.

Also, please note that Bazel toolchains are generated for both: 3.7.2 and 4.1.0 in this repo, so if we want to be strict about the version match, then perhaps we need to import both?

**Comment by wrowe** [comment]
> Also, please note that Bazel toolchains are generated for both: 3.7.2 and 4.1.0 in this repo, so if we want to be strict about the version match, then perhaps we need to import both?

I think we are in the egg-meet-chicken puzzle, or having horses pushing carts.

The envoy bazel environment in the docker image emits this;
```
DEBUG: C:/build/tmp/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
```

But you are right, fresh bazel-toolchain images can conflict with the version of bazel running, and seem to have done so with the first interesting CI failure here.

Reducing our envoy-build-tools to a single bazel 4.1.0 toolchain, first, then we can debug what is still broken about the chosen bazel-toolchain and our tooling/generation logic here.

**Comment by mattklein123** [comment]
Seems like CI is failing.

/wait

**Comment by wrowe** [comment]
This is stale, already at 4.1.0.

**Pull request closed without merging**
