### PR TITLE
Update to LLVM 14.0.0

### PR DESCRIPTION
**Pull request by keith**
More details on https://github.com/envoyproxy/envoy/issues/20803

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by keith** [comment]
Thanks for fixing that @lizan

**Comment by lizan** [comment]
@keith can you also update windows? https://github.com/envoyproxy/envoy-build-tools/blob/main/build_container/build_container_windows.ps1#L130

**Comment by keith** [comment]
Updated, we'll see if that's all it needs

**Comment by keith** [comment]
looks good. @lizan is there anything else we can test before merging this?

**Review by mattklein123 — APPROVED** [review]

**Comment by mattklein123** [comment]
I would just go a ahead and merge. We can sort out other issues when we import?

**Pull request merged**
