### PR TITLE
Add python3.8-dev to the Ubuntu image

### PR DESCRIPTION
**Pull request by lfpino**
The python headers are necessary to build envoy-mobile with remote build execution

### CODE REVIEW

**Comment by phlax** [comment]
hi @lfpino i dont use this image myself, but in my local dev image i have python3.8-dev enabled to allow installing deps that require compilation, so seems a good change to me

would you mind fixing dco - i think the other ci fail was a flake so i have rerun the job

**Comment by phlax** [comment]
ci breakage is unrelated, i opened a pr here #145 to address

**Comment by lfpino** [comment]
@phlax thanks for taking a look! I fixed the DCO now

**Review by phlax — APPROVED** [review]
lgtm, thanks @lfpino

**Pull request merged**
