### PR TITLE
azp agent: expand root device instead

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by lizan** [comment]
@SecurityInsanity

**Comment by SecurityInsanity** [comment]
@lizan I should get you the key for these instances, but AWS does not mount EBS root devices as: `/dev/sda1`. For a 64 bit instance:

```
ssh -T ubuntu@<instance-ip> -i ~/.ssh/aws_cncf_envoy_shared.pem 'lsblk'
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0         7:0    0 93.9M  1 loop /snap/core/9066
loop1         7:1    0   18M  1 loop /snap/amazon-ssm-agent/1566
nvme0n1     259:0    0  200G  0 disk 
└─nvme0n1p1 259:1    0  200G  0 part /
```

And for an ARM instances:

```
ssh -T ubuntu@<arm ip> -i ~/.ssh/aws_cncf_envoy_shared.pem 'lsblk'
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0          7:0    0  83.1M  1 loop /snap/core/9068
loop1          7:1    0  15.4M  1 loop /snap/amazon-ssm-agent/1565
nvme0n1      259:0    0   200G  0 disk 
├─nvme0n1p1  259:1    0 199.9G  0 part /
└─nvme0n1p15 259:2    0    99M  0 part /boot/efi
```

**Comment by lizan** [comment]
@SecurityInsanity yes I know it doesn't mounted as /dev/sda1 at the end, but that's the AMI specifies for root device: `/dev/sda1=snap-0c220f2f0f87f19b0:8:true:gp2:encrypted, /dev/sdb=ephemeral0, /dev/sdc=ephemeral1`. And this worked. (I recycled ASG last night)

**Comment by SecurityInsanity** [comment]
So I see the ARM Hosts being rebuilt, but not the x86, they're still using my AMIs which were buitl with: `/dev/xvda`. I seem to remember all HVMs having: `/dev/xvda` as their root name, but: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html seems to say `/dev/sda1` is still on certain AMIs allowed.

IMO though we should keep with `/dev/xvda` _anyway_ since HVMs don't support things like: `/dev/sda2`, and we're always building HVM compatible AMIs.

**Comment by lizan** [comment]
I recycled both, only rebuilt ARM AMI to update agent version. but both AMI are using `/dev/sda1` as root devices from what I can see in `aws ec2 describe-images`

**Comment by SecurityInsanity** [comment]
Yeah still not a fan of using: `/dev/sda1` on HVM images... IMO that should be changed rather than us changing the override here.

**Pull request merged**
