### PR TITLE
docker/windows: download bazel while building container

### PR DESCRIPTION
**Pull request by akshaysngupta**
This PR attempts to see if bazelisk can be used to download bazel during building the windows container.

### CODE REVIEW

**Comment by phlax** [comment]
fwiw i just kicked `main` ci as github has seems to have fixed a related issue with fetching assets - sadly, same result

**Comment by akshaysngupta** [comment]
@phlax I will try get an expert in windows container networking take a look.

Meanwhile, in the ci for this PR, `build_image` was able to download bazel. Can we run `regenerate_toolchains` now and see if it still tries to download the bazel binary ?

image

**Comment by phlax** [comment]
so the CI does that immediately - it runs toolchain regenerate with the newly minted container

i would kinda expect the same - that bazelisk would now have cached the bazel download - but it doenst appear to have

```console
2023/09/06 07:40:22 Downloading https://releases.bazel.build/6.3.2/release/bazel-6.3.2-windows-x86_64.exe...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 0 packages loaded
    currently loading: 
```

https://github.com/envoyproxy/envoy-build-tools/actions/runs/6093232748/job/16534089560?pr=273#step:10:10

if we could make that work that would be good as workaround for now altho would break when the bazel version changed, and kinda defeats the point of using bazelisk

**Comment by phlax** [comment]
@akshaysngupta if you want we can land this and test to see if it resolves

**Comment by akshaysngupta** [comment]
> 2023/09/06 07:40:22 Downloading https://releases.bazel.build/6.3.2/release/bazel-6.3.2-windows-x86_64.exe...
Here, download is performed by the build agent and not inside the container.

Inside the container, Bazel is invoked by `rbe-config-gen` utility and from the screenshot below, I can see a difference.

In the current CI, bazelisk didn't download bazel
image

While, previously, we would see this:
image

**Comment by akshaysngupta** [comment]
I also feel conflicted that this will defeat the purpose of bazelisk.

On the other hand, I see that we hard-code the version of bazel in the `rbe-config-gen`.
image

**Comment by phlax** [comment]
> On the other hand, I see that we hard-code the version of bazel in the rbe-config-gen.

i noticed that also but came to the conclusion that this was required to _build_ the toolchain - not sure it restricts versions for the work in some way

**Review by phlax — APPROVED** [review]
lgtm, thanks @akshaysngupta  - lets see ...

**Comment by phlax** [comment]
same sadly - https://github.com/envoyproxy/envoy-build-tools/actions/runs/6101329484/job/16558985051#step:5:91

**Comment by akshaysngupta** [comment]
someone suggested running `pktmon` on host machine to debug container networking issues - might be worth a try
https://learn.microsoft.com/en-us/windows-server/networking/technologies/pktmon/pktmon

**Pull request merged**
