### PR TITLE
shellcheck: Update to v0.7.0

### PR DESCRIPTION
**Pull request by phlax**
fixes envoyproxy/envoy#13228

im noticing that the last PR i created - some rebuilding needs to happen to images - not sure what - but i can update if someone lmk

also, when this lands it will break (current) master i think, as there are some lint fails that are not currently being caught - im happy to fix these as/before this lands

### CODE REVIEW

**Comment by mattklein123** [comment]
After this lands it builds an image, and then the image is included by SHA in other places so you can fix things at the same time. Can you check the windows error?

**Comment by sunjayBhatia** [comment]
> After this lands it builds an image, and then the image is included by SHA in other places so you can fix things at the same time. Can you check the windows error?

I was able to download the vs build tools package as expected (https://download.visualstudio.microsoft.com/download/pr/e3850c73-59c6-4c05-9db6-a47a74b67daf/dcb113a854b2cb2141755b6a35c4b9aac6f109081bee45649ec2fcc594b0d7a6/vs_BuildTools.exe) might just need to re-kick the build

**Comment by phlax** [comment]
@sunjayBhatia thanks, ill kick it now

**Comment by sunjayBhatia** [comment]
@phlax in case you need it, see https://github.com/envoyproxy/envoy/pull/12776/files for an example of where all to update the build image tag

**Comment by phlax** [comment]
i meant this bd0e1db46e111345bcbbcc63a1480b418bbb0d88 - but i see now that happens automatically

ill create a PR on envoy for new hashes...

**Comment by mattklein123** [comment]
Can you merge main?

**Comment by phlax** [comment]
eek - one mo...

**Comment by phlax** [comment]
@mattklein123 - im just realizing that we need to land the shellcheck cleanups (envoyproxy/envoy#13362) at same time

might  be better to land the other that updates the hashes pr first

**Review by mattklein123 — APPROVED** [review]

**Comment by phlax** [comment]
@sunjayBhatia the flake seems to be with downloading:

http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20200720.tar.xz

can we put some kind of retry on the download routine ?

**Comment by sunjayBhatia** [comment]
> @sunjayBhatia the flake seems to be with downloading:
> 
> http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20200720.tar.xz
> 
> can we put some kind of retry on the download routine ?

Trying to download that artifact manually and even visit some pages on the msys2 site is failing, that one might not be retryable

**Comment by phlax** [comment]
is there a repo.mysys3.org ?

`8/`

**Pull request merged**
